### ISSUE TITLE
Fork-instructions.md

### ISSUE THREAD

**Issue by irishismyname** [BTCPrivate/BitcoinPrivate#117]
A little confused by the fork instructions. I got through the build/run of the daemon and I let it run for a few seconds before downloading the UTXO snapshot (mistake?).

Then I ran:
`cd ~/.btcprivate/`
`curl https://s3.amazonaws.com/btcp.snapshot/utxo_snapshot.tar.gz | tar xvz`

This is where I'm getting lost, because after this it says to run:
`mkdir ~/.btcprivate`
`touch ~/.btcprivate/btcprivate.conf`

Of course I get the error saying the folder already exists...

So then I run the daemon and it seems to start from scratch downloading blocks and verifying transactions. Was I supposed to point the daemon to the downloaded files? Was I supposed to move them?

**Comment by k4k** [comment]
> Of course I get the error saying the folder already exists...

@irishismyname The `mkdir ~/.btcprivate` step should probably have gone before the `cd ~/.btcprivate` step (otherwise you wouldn't have the `~/.btcprivate` dir, right?) :)

> Was I supposed to point the daemon to the downloaded files? Was I supposed to move them?

I tried a few variations of things to try to use the chainstate files from the desktop wallet on my mining pool node. In doing this, I had also removed `~/.btcprivate/uxto_snapshot`. `btcpd` ultimately core dumped when attempting to start up complaining that this directory was missing. So, to answer your question, I think the daemon expects it there automatically.
