### ISSUE TITLE
Difficulty bomb removal

### ISSUE THREAD

**Issue by mattpass** [BTCPrivate/BitcoinPrivate#204]
The difficulty bomb is due to happen this year and it's been noted it's a good idea to remove it altogether.

Someone will need to look into when it is due to occur and remove it so it doesn't happen.

**Comment by mattpass** [comment]
Looking at code quickly, it seems the difficulty bomb is due to go off on block 600,000:
https://github.com/BTCPrivate/BitcoinPrivate/blob/519ceaa3674faf07376f6ec14be86c692513518d/src/chainparams.cpp#L54

Some quick calculations - if Feb 16th is anticipated to be blockheight 480,000, there's 120,000 left before the bomb.

24 x 60 = 1,440 mins a day. 120,000 / 1,440 = 83.3 days after Feb 16th. Divided by 30 days on average a month = 2.77 months. That means sometime approx around the first half of May.

We should therefore have it disabled ASAP and ensure the codebase that is being used everywhere doesn't include this.

**Comment by bigdaveakers** [comment]
Couple of points...…
What is the logic behind removing it rather than moving it? From a testing point of view moving it to block 1000000 is easier than testing complete removal. I am not a fan of redundant code, but...…..

Second point, your maths is wrong assuming blocks are mined every 2.5 minutes......so more like 6-7 months.....

**Comment by justjamesdev** [comment]
Fixed in https://github.com/BTCPrivate/BitcoinPrivate/pull/235
