### ISSUE TITLE
Proposal to solve Bitcoin's governance problem: Voting Masternodes

### ISSUE THREAD

**Issue by glynmoor** [BTCPrivate/BitcoinPrivate#23]
So a dedicated, multi-sig blockrewarded treasury didn't have sufficient support to pass. I personally voted no on that. However, I'll acknowledge there is a governance problem that should be addressed, and I propose we do so by combining tech from two coins.

I think we should borrow ZenCash's secure nodes and SmartCash's voting system.

I'll start with SmartCash's voting system here: https://vote.smartcash.cc/

As you can see, a large portion of the blockreward goes to a community fund that the community votes on. While we love our devs, there is a lot of hesitation to just allocate them a flat block portion. This voting system makes it so the devs -- and anyone in the community -- can make proposals that the community votes on. These proposals are funded on a need basis. This is very similar to a Monero based proposal/donating system except the funds come from blockrewards. Many people see ideas they like but don’t donate — this lets them support those ideas without having to put up additional funds.

How do you vote and make sure the voters have real skin in the game? By running a securenode (already built on ZenCash) and adding voting power: https://blog.zensystem.io/secure-nodes-why-are-they-important/

I think these features would be the last keys to the puzzle of a premier, truly special privacy coin.

**Comment by gktown** [comment]
It looks like there is a huge amount of money accumulating, (Community Budget = Σ 636,164,791.47 US$ 286,071,219.60) and the majority of proposals are getting denied. Why would miners want to continue to support this fund if it isn't being used? Additionally the majority of these proposals go to help others, but dont neccessarily promote the coin itself.

It sounds good on paper but I think we need to dial it in so that funds don't sit around in an ever-expanding bank account but instead go to support the coin itself.

**Comment by glynmoor** [comment]
That's because the way SmartCash allocates funds from block rewards includes BOTH a developer treasury and then a general community budget. In other words, none of those community funds are supposed to go toward the platform's development.

**Comment by heyrhett** [comment]
Closing this issue for now.  It is not on our roadmap for the first Hard Fork release.
