### ISSUE TITLE
Using BTP as a ticker symbol

### ISSUE THREAD

**Issue by wjcloud** [BTCPrivate/BitcoinPrivate#37]
Hello Bitcoin Private community!
I am wjcloud, a "former" director of Bitcoin Platinum project.

Since Bitcoin Private uses a ticker symbol BTCP, I would like to suggest using a new ticker symbol, BTP.
BTP was used as a ticker of Bitcoin Platinum, however, since the project has been gone I would like to give this opportunity to the better project.

So I have chosen Bitcoin Private for the successor of BTP, and I would support this project from now on.

If anyone pays 1 BTC for the use of the ticker BTP and linking the domain bitcoinplatinum.tech to btcprivate.org, I will gladly watch the project growing up.

Here is my BTC address

bitcoin:329i9MEjuR4uDPp1s91RXADUuVsm52sH5L

**Comment by wjcloud** [comment]
As a proof I've just turned the forwarding address to btcprivate.org check here http://bitcoinplatinum.tech/

**Comment by wjcloud** [comment]
There are some domains for the option.

+ btcplt.org 
+ btpwallet.org
+ btpexp.org

All of the domains are exclusively owned by me, which anyone can't steal those.

**Comment by hsol** [comment]
# DO NOT BUY "BTP" TICKER FROM HIM.

Do not buy "BTP" ticker from him(wjcloud).

He is a wicked terrible cheater to make scam crypto coin.
He advertised to people "We'll hard-fork BTC to BTC Platinum".
But nothing happened on the day he said. So much of people lost their money because of his cheat.

Many have suffered property damage and He have been blocked by various internet communities because he kept scamming there.
When Korean news interviewed him. He said "Sorry to people who lost lot of money and I will not do this again". But watch this issue, Do you think he is reflecting?

Still if you have even a little positive about this issue, Change your opinion and watch this links.
- [Translated wiki about him](https://goo.gl/gnXVR1)
- [Translated news what he interviewed](https://goo.gl/x7SBqc)

@wjcloud If there are not true, comment here to proof you are clear on this problem.

**Comment by wjcloud** [comment]
@hsol Well I am not very related person with a korean or our former korean developer team, If you have any questions on me you can contract though.

**Comment by wjcloud** [comment]
"So much of people lost their money because of his cheat." LOL

**Comment by wjcloud** [comment]
Well I am closing this issue cause I think it is a reckless thing

**Comment by hsol** [comment]
What a poor ghost
