### ISSUE TITLE
Add Replay Protection (for Zclassic and Bitcoin)

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#8]
We need to add replay protection as it is a requirement for many exchanges and wallets.

Here is part of how Bitcoin Cash did it:
https://github.com/Bitcoin-ABC/bitcoin-abc/commit/e49826c1fcc36e5ae26de0ad4d06e2063a759e73

And Bitcoin Gold
With SIGHASH_FORKID
https://github.com/BTCGPU/BTCGPU/pull/109

**Comment by leto** [comment]
I am willing to take this bounty, there is a bounty right???

**Comment by leto** [comment]
I reviewed the original PR that added 2way replay to BTG, which had a bounty specified in BTG which worked out to be 1.2BTC at the time. I am willing to be paid in BTC or ZCL for the bounty.

**Comment by daira** [comment]
Note that Zcash will be doing this as part of our Network Upgrade 0. We're writing a spec now. It is similar in spirit but different in detail to SIGHASH_FORKID. You may not be able to wait for that depending on your schedule, but future Zcash improvements are likely to be *much* easier to integrate if you do.

**Comment by heyrhett** [comment]
@leto and others, we can offer a 1.2 BTC bounty for this if it is implemented properly.

**Comment by leto** [comment]
@heyrhett sounds like a good deal to me, I will be using the `SIGHASH_FORKID` method designed by jl777 and with his guidance

**Comment by kennethffx2** [comment]
Hopefully Zcash dev uses the same method so it isn't a pain in the future to update ZClassic.

**Comment by leto** [comment]
@daira I would love to learn more about the changes you mention, if you can provide any links where I can RTFM, that would be greatly appreciated.

**Comment by leto** [comment]
@heyrhett I will be working in this branch in my fork: 

https://github.com/leto/BitcoinPrivate/tree/2way_replay_protection

I will post occasional updates here to notify y'all of progress. I will probably be constantly rebasing from master or whatever the current tip of dev is, so there may be some back and forth questions required to clarify things that are changing in the moment.

**Comment by daira** [comment]
@leto The draft spec is still on @str4d's machine and in our heads at the moment, but we'll try to get it up on https://github.com/zcash/zips ASAP.

**Comment by akx20000a** [comment]
@daira Does it mean that the un-forked zcash chain will have a value?

**Comment by akx20000a** [comment]
And if we fork via snapshot, we don't need a replay attack protection against Bitcoin.

**Comment by leto** [comment]
@heyrhett I would like to be paid for this implementation, since it is feature complete and has code review from jl777 who designed this super-efficient method of preventing replay attacks across forks.

@akx20000a the above algorithm is the most-efficient two way replay protection (2WRP) that can basically exist. It does not require custom opcodes like the ZEN chain, which make it incompatible with many things and bloats their chain. It only requires changing signature hashing code, which is very unlikely to create merge conflicts with your latest code. I am not sure if you are aware of all the details and implications implicit in the statement you made, but let's agree that "it depends."

The above code protects people who own ZCL who are receiving BTCP, and it protects people who own BTC who are receiving BTCP. 

If the above is agreeable, please pay this BTC address 1.2BTC as agreed: 

128R5qckckLkZ1R1y635YugsiTtoiAmdpZ

![btcp_payment_qr](https://user-images.githubusercontent.com/30298/34542771-db449786-f092-11e7-8022-4ec539f02c51.png)

I am available for any help with merging the code with your latest tip of dev, which does not seem to be public yet. If there is a dev channel to hang out in, please let me know.

**Comment by heyrhett** [comment]
Thank you for the great work!  The bounty has been paid in full and Bitcoin Private is thrilled about the contribution!

**Comment by kennethffx2** [comment]
LETO!!! GODLIKE

**Comment by jb55** [comment]
Whoa actually paying bounties and not cheaping out. Props.

**Comment by airk42** [comment]
The changes in the PR#18 broke the build:
1) 
./script/interpreter.h:92:43: error: left shift count >= width of type [-Werror=shift-count-overflow]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),

./script/interpreter.h:92:40: error: right operand of shift expression ‘(1u << 42)’ is >= than the precision of the left operand [-fpermissive]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),

./script/interpreter.h:92:45: error: enumerator value for ‘SCRIPT_ENABLE_SIGHASH_FORKID’ is not an integer constant
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),

1U - which is unsiged int - is 4 bytes (32 bits) on all 3 OS's (linux, win, mac) in both 32 and 64 versions
shifting it for 42 bits is an error

2)
script/interpreter.cpp:210:38: error: ‘SCRIPT_ERR_ILLEGAL_BTCP_FORKID’ was not declared in this scope

**Comment by airk42** [comment]
Issues 2 has been resolved by PR#28

**Comment by leto** [comment]
@airk42 this should fix the `42 is too big` issue: https://github.com/BTCPrivate/BitcoinPrivate/pull/29

**Comment by airk42** [comment]
@leto Thank you for fixing. Build is working

**Comment by mecampbellsoup** [comment]
@heyrhett hi there - are there any other issues pending which include a bounty similar to this one for BTCP?

**Comment by tearodactyl** [comment]
@daira, did the "similar in spirit but different in detail to SIGHASH_FORKID" method make it into the ZIPs or into the code, please?
